const strings = {
    verifyProceed: 'Verify & Proceed',
    getOtp: 'Get OTP',
    otpVerifcation: 'OTP Verification',
    otpDesciption: 'We will send you ',
    otpDesciptionBold: 'One Time Password on',
    otpDesciptionend: 'this mobile',
    otpDescriptionSecondPart: 'Number or email',
    enterYourMobileNumnerOR: 'Enter your Mobilr no or Email',
    termsPrivacy:'By clicking “Get started”, you are agree to our Terms & Privacy Policy',
    enter4digit:'Please enter the 4 digit OTP code send to',
    haveNotReciviedCode:'Havent receive code?',
    resendVCode:'Resend Code',
    AddPhotoCaption:'Add Photo/Caption',
    AddBusiness:'Add Business',
    AddEvent:'Add Event',
    userName:'Patricia Jhon',
    userEmail:'@Design.chowkbusiness.com',
    Follwing:'Follwing',
    Followers :'Followers',
    Posts:'Posts',
    wallet:'Wallet',
    YourFavourites:'Your Favourites',
    Tickets:'Tickets',
    TellYourFriends:'Tell Your Friends',
    Promotions:'Promotions',
    ChangeYourPassword:'Change Your Password',
    Logout:'Log out',
    youliketoshare:`What would you \n like to share?`,
    SearchUsername:'Search Username',
    postDes:'We deal with the schemes of high games and you \n beautiful people can buy and sell from us.',
    Follow:'Follow',
    FeaturedBusiness:'Featured Business',
    CarWash:'Car Wash',
    RealEstate:'Real Estate',
    FoodCart:'Food Cart',
    ArtDesign:'Art & Design',
    Crytocurrency:'Crytocurrency',
    Pharmacy:'Pharmacy'
}
export default strings