const strings = {
    verifyProceed: 'Verify & Proceed',
    getOtp: 'Get OTP',
    otpVerifcation: 'OTP Verification',
    otpDesciption: 'We will send you ',
    otpDesciptionBold: 'One Time Password on',
    otpDesciptionend: 'this mobile',
    otpDescriptionSecondPart: 'Number or email',
    enterYourMobileNumnerOR: 'Enter your Mobilr no or Email',
    termsPrivacy:'By clicking “Get started”, you are agree to our Terms & Privacy Policy',
    enter4digit:'Please enter the 4 digit OTP code send to',
    haveNotReciviedCode:'Havent receive code?',
    resendVCode:'Resend Code',
    AddPhotoCaption:'Add Photo/Caption',
    AddBusiness:'Add Business',
    AddEvent:'Add Event',
    userName:'Patricia Jhon',
    userEmail:'@Design.chowkbusiness.com',
    Follwing:'Follwing',
    Followers :'Followers',
    Posts:'Posts',
    wallet:'Wallet',
    YourFavourites:'Your Favourites',
    Tickets:'Tickets',
    TellYourFriends:'Tell Your Friends',
    Promotions:'Promotions',
    ChangeYourPassword:'Change Your Password',
    Logout:'Log out',
    youliketoshare:`What would you \n like to share?`,
    SearchUsername:'Search Username',
    postDes:'We deal with the schemes of high games and you \n beautiful people can buy and sell from us.',
    Follow:'Follow',
    FeaturedBusiness:'Featured Business',
    CarWash:'Car Wash',
    RealEstate:'Real Estate',
    FoodCart:'Food Cart',
    ArtDesign:'Art & Design',
    Crytocurrency:'Crytocurrency',
    Pharmacy:'Pharmacy',
    ThisWeek:'This week on',
    thursday:'Thursday',
    FoodDaFiesta:'Food Da Fiesta',
    amount:'$36',
    locationName:'Lipsy, London',
    dateTime:'31 Sat, Mar 2022    6:00 pm',
    Invitefriends:'Invite friends',
    BuyTicket:'Buy Ticket',
    About:'About',
    aboutDes:'If you re looking for a money-making business idea, a food truck is a great one. Successful food trucks can bring in more than $500,000 per year, with startup costs around $40,000. Starting a food truck generally takes three to 12 months and requires these nine steps: Research local food trucks and laws.',
    checkout:'CHECKOUT - ',
    FoodCornerTruck:'Food Corner Truck',
    Readmore:'Read  more',
    BusinessName:'Business Name',
    BusinessCategory:'Business Category',
    BusinessNumber:'Business Number',
    UploadPost:'Upload Post',
    writeCapation:'Write a caption...',
    Addapicturevideo:'Add a picture/video',
    BusinessName:'Business Name'
}
export default strings